### ISSUE TITLE
Create Avatar Initials Utility

### ISSUE THREAD

**Issue by Lanchi** [nsftx/chameleon-sdk#129]
**Is your feature request related to a problem? Please describe.**
As a fallback for all types of avatars/profile pics items we need to show a badge with content initials (where content can be user full name, location name or something else) and coloured background.

Functional requirements:
- utility accepts up to 4 content items
- utility can generate fully random background colour
- utility can generate random background colour from a predefined palette
- utility can generate required background color
- initials are generated from first letters of up to 3 words
- initials letter count default is 2 letters
- when multiple content items are sent, initials can have only one letter
- when multiple content items are sent, initials placeholder should be divided in appropriate parts
- when multiple content items are sent, each part can have different or same background color

**Describe the solution you'd like**
This utility should expose a method that:
- returns a string representing `svg` template. Current control panel implementation can serve as a base to create a template literal and populate it with values.
- accepts two parameters: `content` and `config`
    - `content - {Array{Object}}` - each content item should have `item` and `color` properties
    - `config - {Object}`
        - `config.width - {string}`
        - `config.height - {string}`
        - `config.initialsLength - {number}`
        - `config.colorPalette - {Array{string}}`
        - `config.commonColor - {(boolean|string)}`

Regarding colour priorities: 
- if a content item provided a color, use it for the background (highest priority)
- if a `commonColor` is provided as a color value string, use it for all items
- if `colorPalette` is provided, pick a random color from it
- if no colors are provided, generate a random one
- if `commonColor` is provided as a `boolean` use it in combination with the latter two cases when picking/generating random color

**Additional context**
[Similar lib](https://github.com/judesfernando/initial.js)
Partial implementation in [Control Panel](https://github.com/nsftx/chameleon-control-panel/blob/feature/card/src/components/AvatarInitials.vue)

**Comment by MVucina** [comment]
Will test this on chameleon-menu. 

> - when multiple content items are sent, initials can have only one letter
> - when multiple content items are sent, initials placeholder should be divided in appropriate parts
> - when multiple content items are sent, each part can have different or same background color

T
